name: Baseline Impact Report
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  security-events: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci || npm i
      - name: Run Baseline Impact Copilot (Markdown)
        run: |
          node packages/cli/bin/bic.js scan . --format md --diff --fail-on error > baseline-impact.md || true
      - name: Run Baseline Impact Copilot (SARIF)
        run: |
          node packages/cli/bin/bic.js scan . --format sarif --diff --fail-on error --out baseline-impact.sarif || true
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: baseline-impact.sarif
      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('baseline-impact.md', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
